# Generated by Django 5.1.7 on 2025-03-28 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-created_on']},
        ),
    ]
